# AUTOGENERATED from nimble.lock
# Do not edit manually
{ pkgs }:

{
  bearssl = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-bearssl";
    rev = "b6c9a38964a574f6bc51f69efaf8fb2fedea905e";
    sha256 = "0cv4g2l1pk97qgyy53nqyabpnayr8qx6fw35vjs08zs6af05c4fm";
    fetchSubmodules = true;
  };

  boringssl = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-boringssl";
    rev = "7ec8291f342ffd0f41104cfe60fee819442c6734";
    sha256 = "0wf3ccp88hgh84gpk34d3fzhh7v3wlbik4wxg0gafqqsp5mzn52i";
    fetchSubmodules = true;
  };

  chronicles = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronicles";
    rev = "45c823b8af409f82fa35fd5e1f6a7c9a06fe3137";
    sha256 = "1pl3cs6v4b4l3jk7kifni7sc7jn64alpbkwlh12vwd78knqkqmhf";
    fetchSubmodules = true;
  };

  chronos = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronos";
    rev = "40f8087c815403d64e3dd4044411022cc4bedd5b";
    sha256 = "0vrnl0ha6fp6lb3ic9zd37pbab975s9ghcnw7i0wnfasdhb4pvip";
    fetchSubmodules = true;
  };

  faststreams = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-faststreams";
    rev = "059bc2f52546ac14b583639c33372c14b1d46fa3";
    sha256 = "0xmma6a1b5lgzfqnk1vq3hvf8klbhcab0fnzz4xb68mpdrgvlvk4";
    fetchSubmodules = true;
  };

  httputils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-http-utils";
    rev = "7d771ca337bd3bf563f6834569d2a06085ac21f1";
    sha256 = "0s4pa0g50kmnzl6151pxzil0w0324l0nvfyfbjgvcn0lyflrxjaw";
    fetchSubmodules = true;
  };

  json_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-json-serialization";
    rev = "73c37b46591cf3d6a19d39ff0ed14b2e77433778";
    sha256 = "0fk01rscd5kwdvgv2g3r3wdgbh1cliyjkgdmxc25k11lbkzyp0dl";
    fetchSubmodules = true;
  };

  libp2p = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-libp2p";
    rev = "ab49dc9c09a5c9164840a27bc4da718ace945c5b";
    sha256 = "08bs8l9xldgkd004f40bkg2isszk8c7zb1qm76r2zpx3d7645mxx";
    fetchSubmodules = true;
  };

  libplum = pkgs.fetchgit {
    url = "https://github.com/logos-storage/nim-libplum";
    rev = "189a4984d15f0c60780d6ea5a2ab46bbf6a350f8";
    sha256 = "0nllnpl4mdi58hla0hmx35bkbjmvz4q79wbdmz01vg3qwdnq1r50";
    fetchSubmodules = true;
  };

  lsquic = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-lsquic";
    rev = "f156ed72554d16e925ed654833e7f37e8c8e7f8f";
    sha256 = "0x5laxi1sd5z3ribzp6s8kip1hbr5c0jb2lj8vg3qgk0kjr9g7da";
    fetchSubmodules = true;
  };

  metrics = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-metrics";
    rev = "b56bfb8656bd135f0be17d4da95680e86f71e8b4";
    sha256 = "0zl8hazcmb3mz0wr48dvs6ani9cy7si1i9x6f183n4cmvkrr9flb";
    fetchSubmodules = true;
  };

  nimcrypto = pkgs.fetchgit {
    url = "https://github.com/cheatfate/nimcrypto";
    rev = "b3dbc9c4d08e58c5b7bfad6dc7ef2ee52f2f4c08";
    sha256 = "1v4rz42lwcazs6isi3kmjylkisr84mh0kgmlqycx4i885dn3g0l4";
    fetchSubmodules = true;
  };

  npeg = pkgs.fetchgit {
    url = "https://github.com/zevv/npeg";
    rev = "409f6796d0e880b3f0222c964d1da7de6e450811";
    sha256 = "1h2f5znbpa3svk7wsw2axn8f7f59d23xq85z148kiv6fqh0ffwbm";
    fetchSubmodules = true;
  };

  protobuf_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-protobuf-serialization";
    rev = "a671c6d497c7028ed7390b2d5a80c7b62138c586";
    sha256 = "1i7nid50smfmxvc0zc5cp2xd227ll11r7y261bbj769gpd9bz0ax";
    fetchSubmodules = true;
  };

  results = pkgs.fetchgit {
    url = "https://github.com/arnetheduck/nim-results";
    rev = "df8113dda4c2d74d460a8fa98252b0b771bf1f27";
    sha256 = "1h7amas16sbhlr7zb7n3jb5434k98ji375vzw72k1fsc86vnmcr9";
    fetchSubmodules = true;
  };

  secp256k1 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-secp256k1";
    rev = "d8f1288b7c72f00be5fc2c5ea72bf5cae1eafb15";
    sha256 = "1qjrmwbngb73f6r1fznvig53nyal7wj41d1cmqfksrmivk2sgrn2";
    fetchSubmodules = true;
  };

  serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-serialization";
    rev = "b5473564e80a4908cf6c5a038e4c4a6ca7de2223";
    sha256 = "09abpya7mvcaymxf0n2sc122rq4jkwg9kpis8xyc4z3fx3x3znxk";
    fetchSubmodules = true;
  };

  stew = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-stew";
    rev = "c75502ceedb5ed2a37b7b5e4744fc71313682859";
    sha256 = "10vvsghdchwphpwaqzmjixp01645ki5z5fk225f0i3742hpm6xk4";
    fetchSubmodules = true;
  };

  testutils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-testutils";
    rev = "3feb84e206660d5289caefbe7b0f66f97d9ec084";
    sha256 = "00x5lhp3zkwsrvr98a237shwafa67j1g5wmqgai2qv1djr2ajxgc";
    fetchSubmodules = true;
  };

  unittest2 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-unittest2";
    rev = "26f2ef3ae0ec72a2a75bfe557e02e88f6a31c189";
    sha256 = "1n8n36kad50m97b64y7bzzknz9n7szffxhp0bqpk3g2v7zpda8sw";
    fetchSubmodules = true;
  };

  websock = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-websock";
    rev = "3f7ec0e0241f0abe6b4d6a124c6a2b6755c4b9da";
    sha256 = "1dik9gmivzbhk111hyh2phb1jgwbgr1x1vivnn8khm81jxmg7ynm";
    fetchSubmodules = true;
  };

  zlib = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-zlib";
    rev = "190246aa0bb6569781370964fa2faa474203d6dd";
    sha256 = "0x5l55gwzb1ay3k9inmi1g25jiv7flry247fcwd8rw3zw9pgchfv";
    fetchSubmodules = true;
  };

}
