# AUTOGENERATED from nimble.lock
# Do not edit manually
{ pkgs }:

{
  unittest2 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-unittest2";
    rev = "26f2ef3ae0ec72a2a75bfe557e02e88f6a31c189";
    sha256 = "1n8n36kad50m97b64y7bzzknz9n7szffxhp0bqpk3g2v7zpda8sw";
    fetchSubmodules = true;
  };

  bearssl = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-bearssl";
    rev = "22c6a76ce015bc07e011562bdcfc51d9446c1e82";
    sha256 = "1cvdd7lfrpa6asmc39al3g4py5nqhpqmvypc36r5qyv7p5arc8a3";
    fetchSubmodules = true;
  };

  boringssl = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-boringssl";
    rev = "e77caabae78fbc9aa5b78a0a521181b077c82571";
    sha256 = "15k4dqh1hlcpq9zm30lpr728h7apdmgm22xzqhdm3clq9kia6fr8";
    fetchSubmodules = true;
  };

  results = pkgs.fetchgit {
    url = "https://github.com/arnetheduck/nim-results";
    rev = "df8113dda4c2d74d460a8fa98252b0b771bf1f27";
    sha256 = "1h7amas16sbhlr7zb7n3jb5434k98ji375vzw72k1fsc86vnmcr9";
    fetchSubmodules = true;
  };

  stew = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-stew";
    rev = "4382b18f04b3c43c8409bfcd6b62063773b2bbaa";
    sha256 = "0mx9g5m636h3sk5pllcpylk51brf7lx91izx3gc23k3ih3hrxyk2";
    fetchSubmodules = true;
  };

  faststreams = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-faststreams";
    rev = "50889cd16ec8771106cdd0eeea460039e8571e06";
    sha256 = "1hd4bhvw5lzwg924i8dif5mi61h0ayiplq38djvrdbfsjdhw2zvw";
    fetchSubmodules = true;
  };

  serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-serialization";
    rev = "4092500cea76154576539371709ae801afbd2a9d";
    sha256 = "04pz6d6p3nd1y2khbb667fcd6p2jk4bxv65iaffzq06bqqhalcwc";
    fetchSubmodules = true;
  };

  json_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-json-serialization";
    rev = "c343b0e243d9e17e2c40f3a8a24340f7c4a71d44";
    sha256 = "0i8sq51nqj8lshf6bfixaz9a7sq0ahsbvq3chkxdvv4khsqvam91";
    fetchSubmodules = true;
  };

  testutils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-testutils";
    rev = "6ce5e5e2301ccbc04b09d27ff78741ff4d352b4d";
    sha256 = "1vbkr6i5yxhc2ai3b7rbglhmyc98f99x874fqdp6a152a6kqgwxy";
    fetchSubmodules = true;
  };

  chronicles = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronicles";
    rev = "27ec507429a4eb81edc20f28292ee8ec420be05b";
    sha256 = "1xx9fcfwgcaizq3s7i3s03mclz253r5j8va38l9ycl19fcbc96z9";
    fetchSubmodules = true;
  };

  httputils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-http-utils";
    rev = "f142cb2e8bd812dd002a6493b6082827bb248592";
    sha256 = "03msj4zdxraz4qx9cidb17g7v0asazxv91nng6xxbzjxz0qaqxw6";
    fetchSubmodules = true;
  };

  chronos = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronos";
    rev = "45f43a9ad8bd8bcf5903b42f365c1c879bd54240";
    sha256 = "1v1n59zfzznp97pvwgs9kf136bqmv4x2s2y9f24msspa7qv27w39";
    fetchSubmodules = true;
  };

  nimcrypto = pkgs.fetchgit {
    url = "https://github.com/cheatfate/nimcrypto";
    rev = "b3dbc9c4d08e58c5b7bfad6dc7ef2ee52f2f4c08";
    sha256 = "1v4rz42lwcazs6isi3kmjylkisr84mh0kgmlqycx4i885dn3g0l4";
    fetchSubmodules = true;
  };

  metrics = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-metrics";
    rev = "b4b70a88fe1755d281366cbc3f22d7515240d192";
    sha256 = "0y85na0ah53zk4la8jxjwml9l6269bv21daqn8ylcsd2wg463qs6";
    fetchSubmodules = true;
  };

  secp256k1 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-secp256k1";
    rev = "d8f1288b7c72f00be5fc2c5ea72bf5cae1eafb15";
    sha256 = "1qjrmwbngb73f6r1fznvig53nyal7wj41d1cmqfksrmivk2sgrn2";
    fetchSubmodules = true;
  };

  zlib = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-zlib";
    rev = "190246aa0bb6569781370964fa2faa474203d6dd";
    sha256 = "0x5l55gwzb1ay3k9inmi1g25jiv7flry247fcwd8rw3zw9pgchfv";
    fetchSubmodules = true;
  };

  lsquic = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-lsquic";
    rev = "2f01046bf1d513de8b5f8296c3d8bec819ab0cb9";
    sha256 = "16xj0hx13nc95x7scck8lyir0kzx4wqnd6d4h79aai8j9hlcmbsl";
    fetchSubmodules = true;
  };

  npeg = pkgs.fetchgit {
    url = "https://github.com/zevv/npeg";
    rev = "409f6796d0e880b3f0222c964d1da7de6e450811";
    sha256 = "1h2f5znbpa3svk7wsw2axn8f7f59d23xq85z148kiv6fqh0ffwbm";
    fetchSubmodules = true;
  };

  protobuf_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-protobuf-serialization";
    rev = "cec5f1da897c0b3e6d3a1f2da6a36b4bbdc3a1a8";
    sha256 = "0dmrm8l1293fcmyzm4kmhwplyrd1clrjs8hpf9s9bpbyjw7vf927";
    fetchSubmodules = true;
  };

  websock = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-websock";
    rev = "387a8eb7e961e8fdd3b1a717d36bc53b55e4dc5d";
    sha256 = "1v0m3x96fbp9jdzsys6mbxxc2xw3k3dqiv7wksfla89gc6z8w377";
    fetchSubmodules = true;
  };

  nat_traversal = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-nat-traversal";
    rev = "860e18c37667b5dd005b94c63264560c35d88004";
    sha256 = "0319k5bbl468phwfnvlrh7725sc80rnf7m9gyj0i3cb5hb9q78bs";
    fetchSubmodules = true;
  };

  libp2p = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-libp2p.git";
    rev = "c470b1146fa2ef23ab88c5a0940923cf7645e9c5";
    sha256 = "0y1z5pvpxgajqqdz0fr4zj51z8nimc8z7k6clsnj96wl26v2a5ma";
    fetchSubmodules = true;
  };

}
